// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcb0g1HLI6Fg2gYqq0UhAURjAQ-F2iyEw',
    appId: '1:945724181793:web:6dd15761bd25d0dcc48260',
    messagingSenderId: '945724181793',
    projectId: 'zoomanager',
    authDomain: 'zoomanager.firebaseapp.com',
    storageBucket: 'zoomanager.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7WX2U7HSPkvs_uy2KE_MXRIkXAN7cHnw',
    appId: '1:945724181793:android:dc07f7a54129818bc48260',
    messagingSenderId: '945724181793',
    projectId: 'zoomanager',
    storageBucket: 'zoomanager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq7FkAb8kxQUiAuNuVUPsG-umVrVrommQ',
    appId: '1:945724181793:ios:902df111a815f8e9c48260',
    messagingSenderId: '945724181793',
    projectId: 'zoomanager',
    storageBucket: 'zoomanager.appspot.com',
    iosBundleId: 'com.example.zoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq7FkAb8kxQUiAuNuVUPsG-umVrVrommQ',
    appId: '1:945724181793:ios:64bfc961b2171e03c48260',
    messagingSenderId: '945724181793',
    projectId: 'zoomanager',
    storageBucket: 'zoomanager.appspot.com',
    iosBundleId: 'com.example.zoo.RunnerTests',
  );
}
