// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIDJ3kVB8W6C4j1oRGYrswNvYMsq881QY',
    appId: '1:158871115281:web:bdf0d77e9d949d49b703b0',
    messagingSenderId: '158871115281',
    projectId: 'zoolive-6dd02',
    authDomain: 'zoolive-6dd02.firebaseapp.com',
    storageBucket: 'zoolive-6dd02.appspot.com',
    measurementId: 'G-BLG84YLYVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0SioWx6j5PpZlqCCAzfMG9Zw7YqZdjL0',
    appId: '1:158871115281:android:eeea007b6a3f1a40b703b0',
    messagingSenderId: '158871115281',
    projectId: 'zoolive-6dd02',
    storageBucket: 'zoolive-6dd02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpahhu2AcOoe8B-dqwQTzeWh__PakOAYs',
    appId: '1:158871115281:ios:b02b3987b6ba6303b703b0',
    messagingSenderId: '158871115281',
    projectId: 'zoolive-6dd02',
    storageBucket: 'zoolive-6dd02.appspot.com',
    iosBundleId: 'com.example.zoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpahhu2AcOoe8B-dqwQTzeWh__PakOAYs',
    appId: '1:158871115281:ios:34b4447f33195e45b703b0',
    messagingSenderId: '158871115281',
    projectId: 'zoolive-6dd02',
    storageBucket: 'zoolive-6dd02.appspot.com',
    iosBundleId: 'com.example.zoo.RunnerTests',
  );
}
